# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaca1835b9ed3e1f9384583d01fedaab4ccf2d076e71ad304dc9c2bc6e149b3593810e87a8e139432149c5514b8506d9160c0290df8bd9eed447faf2fe2e7d72

test:
  secret_key_base: 6c71909ef515eb2625d91cd750ecd9e2ea8d49b7fc50511ce43924c1a15f86a6ca9a9eb467f73ac598c31a2874511547a8abeda15703d134bf349ba0c77dd0a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
